---
# defaults file for DPS application

APP: '{{ app_name }}'
JAVA_LOC_ORIG: '/usr/jdk/instances/jdk1.8.0_74/'
env_full_fillment: 'DEV-Development'
PROCESS_NAME: sendmail
APP_PROGRAM_FILE: '/usr/lib/sendmail'
svn_trunk_url: 'https://github.com/johnbashas/Ansible/blob/master'
APP_PORT: 25

#Application file and directory description
UID: P639861
TEMP: '/tmp/{{ UID }}/dps'
DPS_HOME: '/tmp/{{UID }}/local/apps/dps'
DPS_APP_HOME: '{{ DPS_HOME }}/{{ APP }}'
DPS_DIST_DIR: '{{ DPS_HOME }}/dist'
DPS_DEPLOY_DIR: '{{ DPS_HOME }}/deploy'
DPS_LOG_DIR: '{{ DPS_APP_HOME }}/logs'
#BUILD_CONFIRMATION_FILE: '{{ DPS_DEPLOY_DIR }}/bin/build.info'
DPS_APP_LOG_FILE: '{{ DPS_LOG_DIR }}/{{ APP }}.log'

#User details
APP_OWNER: 'u42093'
APP_GROUP: 'u42093'

#Extra vars description
java_loc_orig: '{{ JAVA_LOC_ORIG }}'
dps_var_file_name: 'dump_all_vars_dev_dps.txt'

#Email description
email_attachment_success: "{{ DPS_LOG_DIR }}/{{ APP }}_{{ dps_new_build }}_{{ deploy_start_time }}.log"
email_subject_success: "Deployment Log for {{APP}}"
email_body_success: "Deployment completed for {{APP}} on {{ env_full_fillment }}, Log file : {{ DPS_LOG_DIR }}/{{ APP }}_{{ dps_new_build }}_{{ deploy_start_time }}.log"
DIST_LIST_success: 'basha.tech@gmail.com'

email_attachment_failed: "/tmp/{{ UID }}/local/apps/dps/dist/*.log"
email_subject_failed: "Deployment Failure Log for {{APP}}"
email_body_failed: "Deployment failed for {{APP}} on {{ env_full_fillment }}, Log file : {{ DPS_LOG_DIR }}/Failed_Log_{{ APP }}_{{ deploy_start_time }}.log"
DIST_LIST_failed: 'basha.tech@gmail.com'

MAIL_PORT: 25

# Variable for Fincadservice application.

FIN_APP: '{{ finapp_name }}'
APP_PROGRAM_FILE: '/usr/lib/sendmail'
APP_PROGRAM_FILE_RH: '/usr/sbin/sendmail'
svn_trunk_url: 'https://github.com/johnbashas/Ansible/blob/master'

HOME: '/tmp/{{UID }}/local/apps/fincadservice'
APP_HOME: '{{ HOME }}/{{ FIN_APP }}'
DIST_DIR: '{{ HOME }}/dist'
DEPLOY_DIR: '{{ HOME }}/deploy'
LOG_DIR: '{{ HOME }}/logs'
#FIN_BUILD_CONFIRMATION_FILE: '{{ DEPLOY_DIR }}/bin/build.info'
APP_LOG_FILE: '{{ LOG_DIR }}/{{ FIN_APP }}.log'

var_file_name: 'dump_all_vars_dev_dps.txt'

fin_email_attachment_success: "{{ LOG_DIR }}/{{ FIN_APP }}_{{ new_build }}_{{ deploy_start_time }}.log"
fin_email_subject_success: "Deployment Log for {{FIN_APP}}"
fin_email_body_success: "Deployment completed for {{FIN_APP}} on {{ env_full_fillment }}, Log file : {{ LOG_DIR }}/{{ FIN_APP }}_{{ new_build }}_{{ deploy_start_time }}.log"

fin_email_attachment_failed: "/tmp/{{ UID }}/local/apps/fincadservice/fincadservice/dist/*.log"
fin_email_subject_failed: "Deployment Failure Log for {{FIN_APP}}"
fin_email_body_failed: "Deployment failed for {{ FIN_APP}} on {{ env_full_fillment }}, Log file : {{ LOG_DIR }}/Failed_Log_{{ FIN_APP }}_{{ deploy_start_time }}.log"